# Generated by Django 4.1.4 on 2022-12-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
