# Generated by Django 4.1.4 on 2022-12-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolio_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='photo',
            field=models.ImageField(max_length=255, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
